2023-10-25 13:29:15,500 INFO app MainThread : Data fetched and stored in session successfully at 2023-10-25 13:29:15.500496
2023-10-25 13:29:17,279 ERROR app MainThread : {'message': "module 'os' has no attribute 'getnv'", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/flask-app/app.py", line 85, in index', '    api_url = os.getnv("API_URL") + f"{idorder}"', '              ', "AttributeError: module 'os' has no attribute 'getnv'"]}
2023-10-25 13:34:38,432 INFO app MainThread : Data fetched and stored in session successfully at 2023-10-25 13:34:38.432188
2023-10-25 14:30:46,580 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-25 14:30:46,580 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-25 14:30:46,582 INFO werkzeug MainThread :  * Restarting with stat
2023-10-25 14:30:48,127 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-25 14:30:48,128 INFO werkzeug MainThread :  * Debugger PIN: 122-407-575
2023-10-25 14:31:12,011 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [25/Oct/2023 14:31:12] "GET / HTTP/1.1" 200 -
2023-10-25 14:31:12,119 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [25/Oct/2023 14:31:12] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-25 14:31:13,314 ERROR app Thread-9 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-25 14:31:13,356 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [25/Oct/2023 14:31:13] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-25 14:31:23,042 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-25 14:31:23,042 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-25 14:31:23,043 INFO werkzeug MainThread :  * Restarting with stat
2023-10-25 14:31:24,562 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-25 14:31:24,562 INFO werkzeug MainThread :  * Debugger PIN: 122-407-575
2023-10-25 14:31:33,414 INFO app MainThread : Data fetched and stored in session successfully at 2023-10-25 14:31:33.413936
2023-10-25 14:31:52,365 INFO app MainThread : Data fetched and stored in session successfully at 2023-10-25 14:31:52.365563
2023-10-25 14:42:21,399 INFO app MainThread : Data fetched and stored in session successfully at 2023-10-25 14:42:21.398891
2023-10-25 14:42:36,003 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-25 14:42:36,003 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-25 14:42:36,005 INFO werkzeug MainThread :  * Restarting with stat
2023-10-25 14:42:37,534 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-25 14:42:37,536 INFO werkzeug MainThread :  * Debugger PIN: 122-407-575
2023-10-26 08:49:58,432 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-26 08:49:58,432 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-26 08:49:58,435 INFO werkzeug MainThread :  * Restarting with stat
2023-10-26 08:49:59,949 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-26 08:49:59,950 INFO werkzeug MainThread :  * Debugger PIN: 817-944-264
2023-10-26 08:50:04,338 ERROR app Thread-7 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:50:04,358 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:50:04] "GET / HTTP/1.1" 200 -
2023-10-26 08:50:04,442 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:50:04] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 08:50:04,443 ERROR app Thread-8 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:50:04,445 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:50:04] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 08:50:06,042 ERROR app Thread-10 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:50:06,045 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:50:06] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 08:51:29,595 ERROR app Thread-11 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:51:29,623 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:51:29] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-26 08:51:29,641 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:51:29] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-26 08:51:29,649 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:51:29] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-26 08:51:29,706 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:51:29] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-26 08:51:29,716 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:51:29] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-26 08:52:19,707 ERROR app Thread-16 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:52:19,715 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:52:19] "GET / HTTP/1.1" 200 -
2023-10-26 08:52:19,729 ERROR app Thread-17 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:52:19,731 INFO werkzeug Thread-17 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:52:19] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 08:52:19,735 INFO werkzeug Thread-18 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:52:19] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 08:52:19,761 ERROR app Thread-19 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:52:19,762 INFO werkzeug Thread-19 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:52:19] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 08:53:26,437 ERROR app Thread-20 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:53:26,446 INFO werkzeug Thread-20 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:53:26] "GET / HTTP/1.1" 200 -
2023-10-26 08:53:26,459 ERROR app Thread-21 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:53:26,460 INFO werkzeug Thread-21 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:53:26] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 08:53:26,465 INFO werkzeug Thread-22 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:53:26] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 08:53:26,492 ERROR app Thread-23 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:53:26,494 INFO werkzeug Thread-23 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:53:26] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 08:54:39,794 ERROR app Thread-24 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:54:39,803 INFO werkzeug Thread-24 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:54:39] "GET / HTTP/1.1" 200 -
2023-10-26 08:54:39,818 ERROR app Thread-25 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:54:39,820 INFO werkzeug Thread-25 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:54:39] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 08:54:39,824 INFO werkzeug Thread-26 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:54:39] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 08:54:39,846 ERROR app Thread-27 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:54:39,847 INFO werkzeug Thread-27 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:54:39] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 08:55:07,913 ERROR app Thread-28 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:55:07,921 INFO werkzeug Thread-28 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:07] "GET / HTTP/1.1" 200 -
2023-10-26 08:55:07,935 ERROR app Thread-29 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:55:07,937 INFO werkzeug Thread-29 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:07] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 08:55:07,942 INFO werkzeug Thread-30 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:07] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 08:55:07,982 ERROR app Thread-31 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:55:07,984 INFO werkzeug Thread-31 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:07] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 08:55:22,602 ERROR app Thread-32 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:55:22,611 INFO werkzeug Thread-32 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:22] "GET / HTTP/1.1" 200 -
2023-10-26 08:55:22,626 ERROR app Thread-33 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:55:22,628 INFO werkzeug Thread-33 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:22] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 08:55:22,634 INFO werkzeug Thread-34 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:22] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 08:55:22,663 ERROR app Thread-35 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 08:55:22,664 INFO werkzeug Thread-35 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 08:55:22] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:00:16,434 ERROR app Thread-36 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:00:16,443 INFO werkzeug Thread-36 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:16] "GET / HTTP/1.1" 200 -
2023-10-26 09:00:16,463 ERROR app Thread-37 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:00:16,465 INFO werkzeug Thread-37 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:16] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:00:16,468 INFO werkzeug Thread-38 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:16] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:00:16,487 ERROR app Thread-39 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:00:16,489 INFO werkzeug Thread-39 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:16] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:00:31,386 ERROR app Thread-40 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:00:31,395 INFO werkzeug Thread-40 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:31] "GET / HTTP/1.1" 200 -
2023-10-26 09:00:31,410 ERROR app Thread-41 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:00:31,411 INFO werkzeug Thread-41 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:31] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:00:31,418 INFO werkzeug Thread-42 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:31] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:00:31,443 ERROR app Thread-43 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:00:31,444 INFO werkzeug Thread-43 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:00:31] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:01:08,872 ERROR app Thread-44 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:01:08,881 INFO werkzeug Thread-44 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:08] "GET / HTTP/1.1" 200 -
2023-10-26 09:01:08,905 ERROR app Thread-45 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:01:08,907 INFO werkzeug Thread-45 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:08] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:01:08,911 INFO werkzeug Thread-46 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:08] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:01:08,937 ERROR app Thread-47 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:01:08,939 INFO werkzeug Thread-47 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:08] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:01:51,876 ERROR app Thread-48 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:01:51,885 INFO werkzeug Thread-48 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:51] "GET / HTTP/1.1" 200 -
2023-10-26 09:01:51,898 ERROR app Thread-49 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:01:51,901 INFO werkzeug Thread-49 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:51] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:01:51,904 INFO werkzeug Thread-50 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:51] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:01:51,929 ERROR app Thread-51 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:01:51,931 INFO werkzeug Thread-51 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:01:51] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:02:06,254 ERROR app Thread-52 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:06,264 INFO werkzeug Thread-52 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:06] "GET / HTTP/1.1" 200 -
2023-10-26 09:02:06,277 ERROR app Thread-53 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:06,279 INFO werkzeug Thread-53 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:06] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:02:06,285 INFO werkzeug Thread-54 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:06] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:02:06,311 ERROR app Thread-55 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:06,313 INFO werkzeug Thread-55 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:06] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:02:06,978 ERROR app Thread-56 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:06,980 INFO werkzeug Thread-56 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:06] "GET / HTTP/1.1" 200 -
2023-10-26 09:02:06,994 ERROR app Thread-57 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:06,996 INFO werkzeug Thread-57 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:06] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:02:07,000 INFO werkzeug Thread-58 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:07] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:02:07,025 ERROR app Thread-59 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:07,027 INFO werkzeug Thread-59 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:07] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:02:07,499 ERROR app Thread-60 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:07,501 INFO werkzeug Thread-60 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:07] "GET / HTTP/1.1" 200 -
2023-10-26 09:02:07,514 ERROR app Thread-61 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:07,516 INFO werkzeug Thread-61 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:07] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:02:07,520 INFO werkzeug Thread-62 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:07] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:02:07,543 ERROR app Thread-63 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:07,545 INFO werkzeug Thread-63 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:07] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:02:24,614 ERROR app Thread-64 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:24,628 INFO werkzeug Thread-64 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:24] "GET / HTTP/1.1" 200 -
2023-10-26 09:02:24,645 ERROR app Thread-65 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:24,647 INFO werkzeug Thread-65 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:24] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:02:24,653 INFO werkzeug Thread-66 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:24] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:02:24,683 ERROR app Thread-67 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:24,684 INFO werkzeug Thread-67 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:24] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:02:25,273 ERROR app Thread-68 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:25,275 INFO werkzeug Thread-68 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:25] "GET / HTTP/1.1" 200 -
2023-10-26 09:02:25,287 ERROR app Thread-69 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:25,289 INFO werkzeug Thread-69 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:25] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:02:25,294 INFO werkzeug Thread-70 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:25] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:02:25,310 ERROR app Thread-71 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:02:25,312 INFO werkzeug Thread-71 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:02:25] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:03:43,060 ERROR app Thread-72 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:03:43,069 INFO werkzeug Thread-72 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:03:43] "GET / HTTP/1.1" 200 -
2023-10-26 09:03:43,087 ERROR app Thread-73 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:03:43,089 INFO werkzeug Thread-73 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:03:43] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:03:43,093 INFO werkzeug Thread-74 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:03:43] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:03:43,125 ERROR app Thread-75 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:03:43,127 INFO werkzeug Thread-75 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:03:43] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:04:25,771 ERROR app Thread-76 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:04:25,780 INFO werkzeug Thread-76 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:04:25] "GET / HTTP/1.1" 200 -
2023-10-26 09:04:25,804 ERROR app Thread-77 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:04:25,806 INFO werkzeug Thread-77 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:04:25] "GET /static/style.css HTTP/1.1" 200 -
2023-10-26 09:04:25,813 INFO werkzeug Thread-78 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:04:25] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-26 09:04:25,841 ERROR app Thread-79 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-26 09:04:25,842 INFO werkzeug Thread-79 (process_request_thread) : 127.0.0.1 - - [26/Oct/2023 09:04:25] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-26 09:06:42,399 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/flask-app/app.py', reloading
2023-10-26 09:22:41,638 INFO app MainThread : Data fetched and stored in session successfully at 2023-10-26 09:22:41.637761
